### ISSUE TITLE
只能事先设定好数值？不能根据返回的进度展示？

### ISSUE THREAD

**Issue by 643063150** [Moosphan/Material-ProgressView#2]
如题

**Comment by Moosphan** [comment]
@643063150 之前实现了这个功能，但处于内测阶段，基本已经没问题，这周我会更新一下library。

**Comment by Moosphan** [comment]
@643063150 库已更新到1.0.4，可以通过下载或者上传的进度动态设置progressView的进度值，有问题欢迎再次反馈😄。

**Comment by 643063150** [comment]
哇 更新的很快啊 其实要是有indeterminate功能就更完善了 哈哈  不要求太多  
--

**Comment by Moosphan** [comment]
@643063150 哈哈，只要有人提issue，我基本都会第一时间收到消息的。setProgress方法内部就是调用的刷新方法
