### ISSUE TITLE
Multiple lines in logcat

### ISSUE THREAD

**Issue by Sonphil** [Moosphan/Material-ProgressView#6]
Hello,

The library prints the line "E/Moos-Progress-View: circleBroken>>>>>>no" too many times in the logcat. Can the log be removed?

![image](https://user-images.githubusercontent.com/22182973/45588519-fefed280-b8e3-11e8-8516-17fd82864f35.png)

**Comment by Moosphan** [comment]
@Sonphil OK，i forgot to remove it
